"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var platform_1 = require("./theme/platform");
exports.platform = platform_1.default;
var platform_v3_1 = require("./theme/platform_v3");
exports.platformV3 = platform_v3_1.default;
var platform_hc_1 = require("./theme/platform_hc");
exports.platformHC = platform_hc_1.default;
var platform_hc_v3_1 = require("./theme/platform_hc_v3");
exports.platformHCV3 = platform_hc_v3_1.default;
var q806_v3_1 = require("./theme/q806_v3");
exports.q806V3 = q806_v3_1.default;
var q806_hc_v3_1 = require("./theme/q806_hc_v3");
exports.q806HCV3 = q806_hc_v3_1.default;
