export default interface AntdDarkThemeVariables {
  "@theme"?: string;
  // color palettes
  "@blue-1"?: string;
  "@blue-2"?: string;
  "@blue-3"?: string;
  "@blue-4"?: string;
  "@blue-5"?: string;
  "@blue-6"?: string;
  "@blue-7"?: string;
  "@blue-8"?: string;
  "@blue-9"?: string;
  "@blue-10"?: string;
  "@purple-1"?: string;
  "@purple-2"?: string;
  "@purple-3"?: string;
  "@purple-4"?: string;
  "@purple-5"?: string;
  "@purple-6"?: string;
  "@purple-7"?: string;
  "@purple-8"?: string;
  "@purple-9"?: string;
  "@purple-10"?: string;
  "@cyan-1"?: string;
  "@cyan-2"?: string;
  "@cyan-3"?: string;
  "@cyan-4"?: string;
  "@cyan-5"?: string;
  "@cyan-6"?: string;
  "@cyan-7"?: string;
  "@cyan-8"?: string;
  "@cyan-9"?: string;
  "@cyan-10"?: string;
  "@green-1"?: string;
  "@green-2"?: string;
  "@green-3"?: string;
  "@green-4"?: string;
  "@green-5"?: string;
  "@green-6"?: string;
  "@green-7"?: string;
  "@green-8"?: string;
  "@green-9"?: string;
  "@green-10"?: string;
  "@magenta-1"?: string;
  "@magenta-2"?: string;
  "@magenta-3"?: string;
  "@magenta-4"?: string;
  "@magenta-5"?: string;
  "@magenta-6"?: string;
  "@magenta-7"?: string;
  "@magenta-8"?: string;
  "@magenta-9"?: string;
  "@magenta-10"?: string;
  "@pink-1"?: string;
  "@pink-2"?: string;
  "@pink-3"?: string;
  "@pink-4"?: string;
  "@pink-5"?: string;
  "@pink-6"?: string;
  "@pink-7"?: string;
  "@pink-8"?: string;
  "@pink-9"?: string;
  "@pink-10"?: string;
  "@red-1"?: string;
  "@red-2"?: string;
  "@red-3"?: string;
  "@red-4"?: string;
  "@red-5"?: string;
  "@red-6"?: string;
  "@red-7"?: string;
  "@red-8"?: string;
  "@red-9"?: string;
  "@red-10"?: string;
  "@orange-1"?: string;
  "@orange-2"?: string;
  "@orange-3"?: string;
  "@orange-4"?: string;
  "@orange-5"?: string;
  "@orange-6"?: string;
  "@orange-7"?: string;
  "@orange-8"?: string;
  "@orange-9"?: string;
  "@orange-10"?: string;
  "@yellow-1"?: string;
  "@yellow-2"?: string;
  "@yellow-3"?: string;
  "@yellow-4"?: string;
  "@yellow-5"?: string;
  "@yellow-6"?: string;
  "@yellow-7"?: string;
  "@yellow-8"?: string;
  "@yellow-9"?: string;
  "@yellow-10"?: string;
  "@volcano-1"?: string;
  "@volcano-2"?: string;
  "@volcano-3"?: string;
  "@volcano-4"?: string;
  "@volcano-5"?: string;
  "@volcano-6"?: string;
  "@volcano-7"?: string;
  "@volcano-8"?: string;
  "@volcano-9"?: string;
  "@volcano-10"?: string;
  "@geekblue-1"?: string;
  "@geekblue-2"?: string;
  "@geekblue-3"?: string;
  "@geekblue-4"?: string;
  "@geekblue-5"?: string;
  "@geekblue-6"?: string;
  "@geekblue-7"?: string;
  "@geekblue-8"?: string;
  "@geekblue-9"?: string;
  "@geekblue-10"?: string;
  "@lime-1"?: string;
  "@lime-2"?: string;
  "@lime-3"?: string;
  "@lime-4"?: string;
  "@lime-5"?: string;
  "@lime-6"?: string;
  "@lime-7"?: string;
  "@lime-8"?: string;
  "@lime-9"?: string;
  "@lime-10"?: string;
  "@gold-1"?: string;
  "@gold-2"?: string;
  "@gold-3"?: string;
  "@gold-4"?: string;
  "@gold-5"?: string;
  "@gold-6"?: string;
  "@gold-7"?: string;
  "@gold-8"?: string;
  "@gold-9"?: string;
  "@gold-10"?: string;
  // Color used by default to control hover and active backgrounds and for
  // alert info backgrounds.
  "@primary-1"?: string;
  "@primary-2"?: string;
  "@primary-3"?: string;
  "@primary-4"?: string;
  "@primary-5"?: string;
  "@primary-6"?: string;
  "@primary-7"?: string;
  "@primary-8"?: string;
  "@primary-9"?: string;
  "@primary-10"?: string;
  // Layer background
  "@popover-background"?: string;
  "@popover-customize-border-color"?: string;
  "@body-background"?: string;
  "@component-background"?: string;
  "@text-color"?: string;
  "@text-color-secondary"?: string;
  "@text-color-inverse"?: string;
  "@icon-color-hover"?: string;
  "@heading-color"?: string;
  // The background colors for active and hover states for things like
  // list items or table cells.
  "@item-active-bg"?: string;
  "@item-hover-bg"?: string;
  // Border color
  "@border-color-base"?: string;  // base border outline a component
  "@border-color-split"?: string;  // split border inside a component
  "@background-color-light"?: string;  // background of header and selected item
  "@background-color-base"?: string;  // Default grey background color
  // Disabled states
  "@disabled-color"?: string;
  "@disabled-bg"?: string;
  "@disabled-color-dark"?: string;
  // Tree
  // ---
  "@tree-bg"?: string;
  // List
  // ---
  "@list-customize-card-bg"?: string;
  // Shadow
  // ---
  "@shadow-color"?: string;
  "@shadow-color-inverse"?: string;
  "@box-shadow-base"?: string;
  "@shadow-1-up"?: string;
  "@shadow-1-down"?: string;
  "@shadow-1-right"?: string;
  "@shadow-2"?: string;
  // Buttons
  // ---
  "@btn-shadow"?: string;
  "@btn-primary-shadow"?: string;
  "@btn-text-shadow"?: string;
  "@btn-default-bg"?: string;
  "@btn-default-ghost-color"?: string;
  "@btn-default-ghost-border"?: string;
  "@btn-text-hover-bg"?: string;
  // Checkbox
  // ---
  "@checkbox-check-bg"?: string;
  // Descriptions
  // ---
  "@descriptions-bg"?: string;
  // Divider
  // ---
  "@divider-color"?: string;
  // Modal
  // ---
  "@modal-header-bg"?: string;
  "@modal-header-border-color-split"?: string;
  "@modal-content-bg"?: string;
  "@modal-footer-border-color-split"?: string;
  // Radio
  // ---
  "@radio-solid-checked-color"?: string;
  "@radio-dot-disabled-color"?: string;
  // Radio buttons
  // ---
  "@radio-disabled-button-checked-bg"?: string;
  "@radio-disabled-button-checked-color"?: string;
  // Layout
  // ---
  "@layout-body-background"?: string;
  "@layout-header-background"?: string;
  "@layout-trigger-background"?: string;
  // Input
  // ---
  "@input-bg"?: string;
  "@input-placeholder-color"?: string;
  "@input-icon-color"?: string;
  "@input-number-handler-active-bg"?: string;
  "@input-icon-hover-color"?: string;
  // Select
  // ---
  "@select-background"?: string;
  "@select-dropdown-bg"?: string;
  "@select-clear-background"?: string;
  "@select-selection-item-bg"?: string;
  "@select-selection-item-border-color"?: string;
  "@select-multiple-disabled-background"?: string;
  "@select-multiple-item-disabled-color"?: string;
  "@select-multiple-item-disabled-border-color"?: string;
  // Cascader
  // ---
  "@cascader-bg"?: string;
  "@cascader-menu-bg"?: string;
  "@cascader-menu-border-color-split"?: string;
  // Tooltip
  // ---
  // Tooltip background color
  "@tooltip-bg"?: string;
  // Menu
  // ---
  // dark theme
  "@menu-dark-submenu-bg"?: string;
  "@menu-dark-bg"?: string;
  "@menu-popup-bg"?: string;
  // Message
  // ---
  "@message-notice-content-bg"?: string;
  // Notification
  "@notification-bg"?: string;
  // LINK
  "@link-hover-color"?: string;
  "@link-active-color"?: string;
  // Table
  // --
  "@table-header-bg"?: string;
  "@table-body-sort-bg"?: string;
  "@table-row-hover-bg"?: string;
  "@table-header-sort-bg"?: string;
  "@table-header-filter-active-bg"?: string;
  "@table-header-sort-active-bg"?: string;
  "@table-filter-btns-bg"?: string;
  "@table-expanded-row-bg"?: string;
  "@table-filter-dropdown-bg"?: string;
  "@table-expand-icon-bg"?: string;
  // TimePicker
  // ---
  "@picker-basic-cell-hover-with-range-color"?: string;
  "@picker-basic-cell-disabled-bg"?: string;
  "@picker-border-color"?: string;
  "@picker-bg"?: string;
  "@picker-date-hover-range-border-color"?: string;
  // Dropdown
  // ---
  "@dropdown-menu-bg"?: string;
  "@dropdown-menu-submenu-disabled-bg"?: string;
  // Steps
  // ---
  "@steps-nav-arrow-color"?: string;
  "@steps-background"?: string;
  // Avatar
  // ---
  "@avatar-bg"?: string;
  // Progress
  // ---
  "@progress-steps-item-bg"?: string;
  // Calendar
  // ---
  "@calendar-bg"?: string;
  "@calendar-input-bg"?: string;
  "@calendar-border-color"?: string;
  "@calendar-full-bg"?: string;
  // Badge
  // ---
  "@badge-text-color"?: string;
  // Popover
  "@popover-bg"?: string;
  // Drawer
  "@drawer-bg"?: string;
  // Card
  // ---
  "@card-actions-background"?: string;
  "@card-skeleton-bg"?: string;
  "@card-shadow"?: string;
  // Transfer
  // ---
  "@transfer-item-hover-bg"?: string;
  // Comment
  // ---
  "@comment-bg"?: string;
  "@comment-author-time-color"?: string;
  "@comment-action-hover-color"?: string;
  // Rate
  // ---
  "@rate-star-bg"?: string;
  // Switch
  // ---
  "@switch-bg"?: string;
  // Pagination
  // ---
  "@pagination-item-bg"?: string;
  "@pagination-item-bg-active"?: string;
  "@pagination-item-link-bg"?: string;
  "@pagination-item-disabled-bg-active"?: string;
  "@pagination-item-disabled-color-active"?: string;
  "@pagination-item-input-bg"?: string;
  // PageHeader
  // ---
  "@page-header-back-color"?: string;
  "@page-header-ghost-bg"?: string;
  // Slider
  // ---
  "@slider-rail-background-color"?: string;
  "@slider-rail-background-color-hover"?: string;
  "@slider-dot-border-color"?: string;
  "@slider-dot-border-color-active"?: string;
  // Skeleton
  // ---
  "@skeleton-color"?: string;
  "@skeleton-to-color"?: string;
  // Alert
  // ---
  "@alert-success-border-color"?: string;
  "@alert-success-bg-color"?: string;
  "@alert-success-icon-color"?: string;
  "@alert-info-border-color"?: string;
  "@alert-info-bg-color"?: string;
  "@alert-info-icon-color"?: string;
  "@alert-warning-border-color"?: string;
  "@alert-warning-bg-color"?: string;
  "@alert-warning-icon-color"?: string;
  "@alert-error-border-color"?: string;
  "@alert-error-bg-color"?: string;
  "@alert-error-icon-color"?: string;
  // Timeline
  // ---
  "@timeline-color"?: string;
  "@timeline-dot-color"?: string;
  // Mentions
  // ---
  "@mentions-dropdown-bg"?: string;
}