"use strict";

const path = require("path");
const fs = require("fs");

const libPath = path.join(__dirname, "../lib");
const themePath = path.join(libPath, "theme");
const lessFilenameSuffix = ".theme.less";
const lessFileForeword = `// Generated by @jimengio/jimo-antd-theme\n\n`;

/**
 * Generate `*.theme.less` files with `lib/theme/*.js`
 */
module.exports = function GenerateLessFile() {
  const files = fs.readdirSync(themePath);

  if (!files) {
    throw new Error(`No files in '${themePath}'.`);
  }

  files.filter(isJsFile).map(filename => {
    const obj = require(path.join(themePath, filename)).default;

    if (!obj) {
      throw new Error(`No default data in '${filename}': ${obj}.`);
    }

    let content = lessFileForeword;

    Object.keys(obj).map(k => (content += `${k}: ${obj[k]};\n`));

    const lessFile = path.join(libPath, fmtNameJs2Less(filename));
    fs.writeFileSync(lessFile, content);
    console.info(`Generated ${lessFile}`);
  });
};

function isJsFile(filename) {
  return /\w+.js$/.test(filename);
}

function fmtNameJs2Less(filename) {
  return filename.replace(/.js$/, lessFilenameSuffix);
}

process.nextTick(() => require.main.exports());
