"use strict";

const path = require("path");
const fs = require("fs");

const libPath = path.join(__dirname, "../lib");
const lessFileNameSuffix = ".theme.less";
const lessFileForeword = `// Generated by @jimengio/jimo-antd-theme\n\n`;

module.exports = function GenerateLessFile() {
  const files = fs.readdirSync(libPath);

  files.filter(isLessJsFile).map(f => {
    const obj = require(path.join(libPath, f)).default;

    let content = lessFileForeword;

    Object.keys(obj).map(k => (content += `${k}: ${obj[k]};\n`));

    const lessFile = path.join(libPath, fmtNameJs2Less(f));
    fs.writeFileSync(lessFile, content);
    console.info(`Generated ${lessFile}`);
  });
};

function isLessJsFile(fileName) {
  return /\w+.js$/.test(fileName) && !/index.js$/.test(fileName);
}

function fmtNameJs2Less(file) {
  return file.replace(/.js$/, lessFileNameSuffix);
}

process.nextTick(() => require.main.exports());
